# Generated by Django 3.0.4 on 2020-04-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='firstname', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='lastname', max_length=20),
            preserve_default=False,
        ),
    ]
