# Generated by Django 3.0.4 on 2020-04-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20200402_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
