# Generated by Django 3.0.4 on 2020-04-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarterback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=-1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
