# Generated by Django 3.0.4 on 2020-04-13 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_quarterback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarterback',
            name='age',
        ),
        migrations.AddField(
            model_name='quarterback',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='composite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='interceptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='past_PPG',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='past_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='pos_tier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='projected_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='rushing_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='rushing_touchdowns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='rushing_yds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='tier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='touchdowns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_short_name',
            field=models.CharField(max_length=3),
        ),
        migrations.CreateModel(
            name='WideReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('past_points', models.IntegerField(default=0)),
                ('past_PPG', models.IntegerField(default=0)),
                ('projected_rank', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('tier', models.IntegerField(default=0)),
                ('pos_tier', models.IntegerField(default=0)),
                ('composite', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TightEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('past_points', models.IntegerField(default=0)),
                ('past_PPG', models.IntegerField(default=0)),
                ('projected_rank', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('tier', models.IntegerField(default=0)),
                ('pos_tier', models.IntegerField(default=0)),
                ('composite', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunningBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('past_points', models.IntegerField(default=0)),
                ('past_PPG', models.IntegerField(default=0)),
                ('projected_rank', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('tier', models.IntegerField(default=0)),
                ('pos_tier', models.IntegerField(default=0)),
                ('composite', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('past_points', models.IntegerField(default=0)),
                ('past_PPG', models.IntegerField(default=0)),
                ('projected_rank', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('tier', models.IntegerField(default=0)),
                ('pos_tier', models.IntegerField(default=0)),
                ('composite', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('past_points', models.IntegerField(default=0)),
                ('past_PPG', models.IntegerField(default=0)),
                ('projected_rank', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('tier', models.IntegerField(default=0)),
                ('pos_tier', models.IntegerField(default=0)),
                ('composite', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
