# Generated by Django 3.0.4 on 2020-04-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20200417_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defense',
            name='composite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='defense',
            name='past_PPG',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='defense',
            name='past_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kicker',
            name='composite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kicker',
            name='past_PPG',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kicker',
            name='past_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quarterback',
            name='composite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quarterback',
            name='past_PPG',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quarterback',
            name='past_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='runningback',
            name='composite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='runningback',
            name='past_PPG',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='runningback',
            name='past_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tightend',
            name='composite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tightend',
            name='past_PPG',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tightend',
            name='past_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='widereceiver',
            name='composite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='widereceiver',
            name='past_PPG',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='widereceiver',
            name='past_points',
            field=models.FloatField(default=0),
        ),
    ]
