# Generated by Django 3.0.4 on 2020-04-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20200417_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defense',
            name='passing_ypg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='defense',
            name='rushing_ypg',
            field=models.FloatField(default=0),
        ),
    ]
